# 1.张量的创建

学习目标

- 掌握张量创建

PyTorch 是一个 Python 深度学习框架，它将数据封装成张量(Tensor)来进行运算。

PyTorch 中的张量就是元素为同一种数据类型的多维矩阵。

在PyTorch 中，张量以"类”的形式封装起来对张量的一些运算、处理的方法被封装在类中。

## 1.基本创建方式

1. torch.tensor 根据指定数据创建张量

2. torch.Tensor 根据形状创建张量,其也可用来创建指定数据的张量

3. torch.IntTensor、torch.FloatTensor、torch.DoubleTensor 创建指定类型的张量

In [3]:
import torch
import numpy as np
import random

# 1. 根据已有数据创建张量
def test01():

    # 1. 创建张量标量
    data = torch.tensor(10)
    print(data)

    # 2. numpy 数组，由于 data 为 float64，下面代码也使用该类型
    data = np.random.randn(2, 3)
    data = torch.tensor(data)
    print(data)

    # 3. 列表，下面代码使用默认元素类型 float32
    data = [[10., 20., 30.], [40., 50., 60.]]
    data = torch.tensor(data)
    print(data)


# 2. 创建指定形状的张量
def test02():

    # 1. 创建2行3列的张量，默认 dtype 为 float32
    data = torch.Tensor(2, 3)
    print(data)

    # 2. 注意：如果传递列表，则创建包含指定元素的张量
    data = torch.Tensor([10])
    print(data)

    data = torch.Tensor([10, 20])
    print(data)

# 3. 使用具体类型的张量
def test03():
    # 1. 创建2行3列，dtype为int32的张量
    data = torch.IntTensor(2, 3)
    print(data)

    # 2. 注意：如果传递的元素类型不正确，则会进行类型转换
    data = torch.IntTensor([2.5, 3.3])
    print(data)

    # 3. 其他的类型
    data = torch.ShortTensor()   # int16
    data = torch.LongTensor()    # int64
    data = torch.FloatTensor()   # float32
    data = torch.DoubleTensor()  # float64


if __name__ == '__main__':
    test01()

tensor(10)
tensor([[-0.5049,  0.9782,  0.0645],
        [ 0.8818,  0.5554,  1.4214]], dtype=torch.float64)
tensor([[10., 20., 30.],
        [40., 50., 60.]])


## 2.创建线性和随机张量

1. torch.arange 和torch.linspace 创建线性张量

2. toreh.random.init_seed和torch.random.manual_seed 随机种子设置

3. torch.randn 创建随机张量

In [6]:
import torch

# 1. 创建线性空间的张量
def test01():

    # 1. 在指定区间按照步长生成元素 [start, end, step)
    data = torch.arange(0, 10, 2)
    print(data)

    # 2. 在指定区间按照元素个数生成
    data = torch.linspace(0, 11, 10)
    print(data)


# 2. 创建随机张量
def test02():

    # 1. 创建随机张量
    data = torch.randn(2, 3) # 创建2行3列张量
    print(data)

    # 2. 随机数种子设置
    print('随机数种子:', torch.random.initial_seed())
    torch.random.manual_seed(100)
    print('随机数种子:', torch.random.initial_seed())

# 3. 随机种子的复现作用测试
def test03():
    # 设置随机种子
    torch.random.manual_seed(100)

    # 创建一个随机初始化的张量
    tensor1 = torch.randn(3, 3)
    print("Tensor 1:\n", tensor1)

    # 再次设置相同的随机种子
    torch.random.manual_seed(100)

    # 再次创建一个随机初始化的张量
    tensor2 = torch.randn(3, 3)
    print("Tensor 2:\n", tensor2)

    # 检查两个张量是否相同
    print("Are tensors equal?", torch.equal(tensor1, tensor2))


if __name__ == '__main__':
    test03()

Tensor 1:
 tensor([[ 0.3607, -0.2859, -0.3938],
        [ 0.2429, -1.3833, -2.3134],
        [-0.3172, -0.8660,  1.7482]])
Tensor 2:
 tensor([[ 0.3607, -0.2859, -0.3938],
        [ 0.2429, -1.3833, -2.3134],
        [-0.3172, -0.8660,  1.7482]])
Are tensors equal? True


## 3.创建01张量

1. torch.ones 和torch.ones_like 创建全1张量

2. torch.zeros和torch.zeros_like 创建全0张量

3. torch.full 和 torch.full_like 创建全为指定值张量

In [7]:
import torch

# 1. 创建全0张量
def test01():

    # 1. 创建指定形状全0张量
    data = torch.zeros(2, 3)
    print(data)

    # 2. 根据张量形状创建全0张量
    data = torch.zeros_like(data)
    print(data)


# 2. 创建全1张量
def test02():

    # 1. 创建指定形状全1张量
    data = torch.ones(2, 3)
    print(data)

    # 2. 根据张量形状创建全1张量
    data = torch.ones_like(data)
    print(data)

# 3. 创建全为指定值的张量
def test03():

    # 1. 创建指定形状指定值的张量
    data = torch.full([2, 3], 10)
    print(data)

    # 2. 根据张量形状创建指定值的张量
    data = torch.full_like(data, 20)
    print(data)


if __name__ == '__main__':
    test01()
    test02()
    test03()

tensor([[0., 0., 0.],
        [0., 0., 0.]])
tensor([[0., 0., 0.],
        [0., 0., 0.]])
tensor([[1., 1., 1.],
        [1., 1., 1.]])
tensor([[1., 1., 1.],
        [1., 1., 1.]])
tensor([[10, 10, 10],
        [10, 10, 10]])
tensor([[20, 20, 20],
        [20, 20, 20]])


## 4.张量元素类型转换

1. tensor.type(torch.DoubleTensor)

2. torch.double0



In [9]:
import torch


def test():

    data = torch.full([2, 3], 10)
    print(data.dtype)

    # 将 data 元素类型转换为 float64 类型

    # 1. 第一种方法
    data = data.type(torch.DoubleTensor)
    print(data.dtype)

    # 转换为其他类型
    # data = data.type(torch.ShortTensor)
    # data = data.type(torch.IntTensor)
    # data = data.type(torch.LongTensor)
    # data = data.type(torch.FloatTensor)

    # 2. 第二种方法
    data = data.double()
    print(data.dtype)

    # 转换为其他类型
    # data = data.short()
    # data = data.int()
    # data = data.long()
    # data = data.float()


if __name__ == '__main__':
    test()

torch.int64
torch.float64
torch.float64


# 2.张量数值计算

学习目标

- 掌握张量基本运算

- 掌握阿达玛积、点积运算

- 掌握PyTorch指定运算设备

PyTorch 计算的数据都是以张量形式存在，我们需要掌握张量各种运算。

并且，我们可以在 CPU 中运算,也可以在 GPU 中运算.

## 1.张量基本运算

基本运算中，包括 add、sub、mul、div、neg等函数,以及这些函数的带下划线的版本 add_、sub_、mul_、div_、neg_其中带下划线的版本为修改原数据。

In [1]:
import numpy as np
import torch


def test():

    data = torch.randint(0, 10, [2, 3])
    print(data)
    print('-' * 50)

    # 1. 不修改原数据
    new_data = data.add(10)  # 等价 new_data = data + 10
    print(new_data)
    print('-' * 50)

    # 2. 直接修改原数据
    # 注意：带下划线的函数为修改原数据本身
    data.add_(10)  # 等价 data += 10
    print(data)

    # 3. 其他函数
    print(data.sub(100))
    print(data.mul(100))
    print(data.div(100))
    print(data.neg())

if __name__ == '__main__':
    test()

tensor([[4, 0, 6],
        [6, 9, 1]])
--------------------------------------------------
tensor([[14, 10, 16],
        [16, 19, 11]])
--------------------------------------------------
tensor([[14, 10, 16],
        [16, 19, 11]])
tensor([[-86, -90, -84],
        [-84, -81, -89]])
tensor([[1400, 1000, 1600],
        [1600, 1900, 1100]])
tensor([[0.1400, 0.1000, 0.1600],
        [0.1600, 0.1900, 0.1100]])
tensor([[-14, -10, -16],
        [-16, -19, -11]])


## 2.阿达玛积

阿达玛积指的是矩阵对应位置的元素相乘.

In [ ]:
import numpy as np
import torch


def test():

    data1 = torch.tensor([[1, 2], [3, 4]])
    data2 = torch.tensor([[5, 6], [7, 8]])

    # 第一种方式
    data = torch.mul(data1, data2)
    print(data)
    print('-' * 50)

    # 第二种方式
    data = data1 * data2
    print(data)
    print('-' * 50)

if __name__ == '__main__':
    test()

tensor([[ 5, 12],
        [21, 32]])
--------------------------------------------------
tensor([[ 5, 12],
        [21, 32]])
--------------------------------------------------


## 3. 点积运算

点积运算要求第一个矩阵 shape: (n, m), 第二个矩阵 shape: (m, p), 两个矩阵点积运算 shape 为: (n, p)。

1. 运算符 @ 用于进行两个矩阵的点乘运算

2. torch.mm 用于进行两个矩阵点乘运算, 要求输入的矩阵为2维

3. torch.bmm 用于批量进行矩阵点乘运算, 要求输入的矩阵为3维

4. torch.matmul 对进行点乘运算的两矩阵形状没有限定.

    a. 对于输入都是二维的张量相当于 mm 运算.

    b. 对于输入都是三维的张量相当于 bmm 运算
 
    c. 对数输入的 shape 不同的张量, 对应的最后几个维度必须符合矩阵运算规则

In [ ]:
import numpy as np
import torch

# 1. 点积运算
def test01():

    data1 = torch.tensor([[1, 2], [3, 4], [5, 6]])
    data2 = torch.tensor([[5, 6], [7, 8]])

    # 第一种方式
    data = data1 @ data2
    print(data)
    print('-' * 50)

    # 第二种方式
    data = torch.mm(data1, data2)
    print(data)
    print('-' * 50)

    # 第三种方式
    data = torch.matmul(data1, data2)
    print(data)
    print('-' * 50)

# # 2. torch.mm 和 torch.matmul 的区别
def test02():

    # matmul可以两个维度可以不同
    # 第一个张量：(3, 4, 5)
    # 第二个张量：(5, 4)
    # torch.mm不可以相乘，而matmul则可以相乘

    print(torch.matmul(torch.randn(3, 4, 5), torch.randn(5, 4)).shape)
    print(torch.matmul(torch.randn(5, 4), torch.randn(3, 4, 5)).shape)

# # 3. torch.mm函数的用法
def test03():

    # 批量点积运算
    # 第一个维度为batch_size
    # 矩阵的二，三维要满足矩阵乘法规则

    data1 = torch.randn(3, 4, 5)
    data2 = torch.randn(3, 5, 8)

    data = torch.bmm(data1, data2)
    print(data.shape)

if __name__ == '__main__':
    test01()
    test02()
    test03()

torch.Size([3, 4, 4])
torch.Size([3, 5, 5])


## 4.指定运算设备

PyTorch 默认会将张量创建在 CPU 控制的内存中，即：默认的运算设备为 CPU。

我们也可以将张量创建在 GPU 上，能够利用对于矩阵计算的优势加快模型训练。

将张量移动到 GPU 上有两种方法：

1. 使用 cuda 方法 

2. 直接在 GPU 上创建张量 

3. 使用 to 方法指定设备

In [9]:
import torch


# 1. 使用 cuda 方法
def test01():

    data = torch.tensor([10, 20, 30])
    print('存储设备:', data.device)

    # 如果安装的不是 gpu 版本的 PyTorch
    # 或电脑本身没有 NVIDIA 卡的计算环境
    # 下面代码可能会报错
    data = data.cuda()
    print('存储设备:', data.device)

    # 使用 cpu 函数将张量移动到 cpu 上
    data = data.cpu()
    print('存储设备:', data.device)

    # 输出结果：
    # 存储设备：cpu
    # 存储设备：cuda:0
    # 存储设备：cpu


# 2. 直接将张量创建在 GPU 上
def test02():

    data = torch.tensor([10, 20, 30], device='cuda:0')
    print('存储设备:', data.device)

    # 使用 cpu 函数将张量移动到 cpu 上
    data = data.cpu()
    print('存储设备:', data.device)

    # 输出结果：
    # 存储设备：cuda:0
    # 存储设备：cpu

# 3. 使用 to 方法
def test03():

    data = torch.tensor([10, 20, 30])
    print('存储设备:', data.device)

    data = data.to('cuda:0')
    print('存储设备:', data.device)

    # 输出结果：
    # 存储设备：cpu
    # 存储设备：cuda:0

# 4. 存储在不同设备的张量不能运算
def test04():

    data1 = torch.tensor([10, 20, 30], device='cuda:0')
    data2 = torch.tensor([10, 20, 30])
    print(data1.device, data2.device)

    # RuntimeError: Expected all tensors to be on the same device,
    # but found at least two devices, cuda:0 and cpu!
    data = data1 + data2
    print(data)


if __name__ == '__main__':
    test03()

存储设备: cpu


AssertionError: Torch not compiled with CUDA enabled

# 3.张量类型转换

学习目标
- 掌握张量类型转换方法

张量的类型转换也是经常使用的一种操作，是必须掌握的知识点。在本小节，我们主要学习如何将 numpy 数组和 PyTorch Tensor 的转化方法。

## 1. 张量转换为 numpy 数组

使用 `Tensor.numpy()` 函数可以将张量转换为 ndarray 数组，但是共享内存，可以使用 `copy()` 函数避免共享。

In [10]:
# 1. 将张量转换为 numpy 数组
def test01():

    data_tensor = torch.tensor([2, 3, 4])
    # 使用张量对象中的 numpy 函数进行转换
    data_numpy = data_tensor.numpy()

    print(type(data_tensor))
    print(type(data_numpy))

    # 注意: data_tensor 和 data_numpy 共享内存
    # 修改其中的一个，另外一个也会发生改变
    # data_tensor[0] = 100
    data_numpy[0] = 100

    print(data_tensor)
    print(data_numpy)


if __name__ == '__main__':
    test01()

<class 'torch.Tensor'>
<class 'numpy.ndarray'>
tensor([100,   3,   4])
[100   3   4]


## 2. numpy 转换为张量

1. 使用 `from_numpy` 可以将 ndarray 数组转换为 Tensor，默认共享内存，使用 `copy` 函数避免共享。
2. 使用 `torch.tensor` 可以将 ndarray 数组转换为 Tensor，默认不共享内存。

In [11]:
# 1. 使用 from_numpy 函数
def test01():

    data_numpy = np.array([2, 3, 4])
    # 将 numpy 数组转换为张量类型
    # 1. from_numpy
    # 2. torch.tensor(ndarray)

    # 浅拷贝
    data_tensor = torch.from_numpy(data_numpy)

    # numpy 和 tensor 共享内存
    # data_numpy[0] = 100
    data_tensor[0] = 100

    print(data_tensor)
    print(data_numpy)

# 2. 使用 torch.tensor 函数
def test02():

    data_numpy = np.array([2, 3, 4])

    data_tensor = torch.tensor(data_numpy)

    # numpy 和 tensor 不共享内存
    # data_numpy[0] = 100
    data_tensor[0] = 100

    print(data_tensor)
    print(data_numpy)


if __name__ == '__main__':
    test01()
    test02()

tensor([100,   3,   4])
[100   3   4]
tensor([100,   3,   4])
[2 3 4]


## 3. 标量张量和数字的转换

对于只有一个元素的张量，使用 `item` 方法将该值从张量中提取出来。

In [12]:
# 3. 标量张量和数字的转换
def test03():

    # 当张量只包含一个元素时，可以通过 item 函数提取出该值
    data = torch.tensor([30,])
    print(data.item())

    data = torch.tensor(30)
    print(data.item())


if __name__ == '__main__':
    test03()

30
30


# 4 张量拼接操作

学习目标
- 掌握 torch.cat torch.stack 使用

张量的拼接操作在神经网络搭建过程中是非常常用的方法，例如：在后面将要学习到的残差网络、注意力机制中都使用到了张量拼接。

## 1. torch.cat 函数的使用

`torch.cat` 函数可以将两个张量根据指定的维度拼接起来。

In [26]:
import torch


def test():

    data1 = torch.randint(0, 10, [3, 5, 4])
    data2 = torch.randint(0, 10, [3, 5, 4])

    print(data1)
    print(data2)
    print('-' * 50)

    # 1. 按 0 维度拼接
    new_data = torch.cat([data1, data2], dim=0)
    print(new_data.shape)
    print('-' * 50)
    print(new_data)
    print('-' * 50)

    # 2. 按 1 维度拼接
    new_data = torch.cat([data1, data2], dim=1)
    print(new_data.shape)
    print('-' * 50)
    print(new_data)
    print('-' * 50)

    # 3. 按 2 维度拼接
    new_data = torch.cat([data1, data2], dim=2)
    print(new_data.shape)
    print(new_data)
    print('-' * 50)

if __name__ == '__main__':
    test()

tensor([[[3, 3, 2, 3],
         [4, 4, 2, 4],
         [8, 5, 5, 2],
         [4, 3, 3, 5],
         [2, 8, 4, 5]],

        [[2, 2, 9, 1],
         [4, 7, 9, 5],
         [4, 2, 0, 7],
         [2, 7, 5, 3],
         [6, 7, 4, 2]],

        [[9, 2, 0, 5],
         [7, 9, 4, 5],
         [4, 2, 0, 6],
         [4, 5, 0, 4],
         [9, 3, 8, 2]]])
tensor([[[6, 8, 0, 9],
         [9, 5, 5, 7],
         [7, 2, 3, 6],
         [4, 8, 5, 5],
         [9, 0, 6, 6]],

        [[4, 9, 7, 1],
         [8, 7, 9, 0],
         [8, 4, 6, 8],
         [6, 7, 3, 7],
         [4, 6, 3, 5]],

        [[9, 9, 7, 9],
         [2, 2, 5, 7],
         [4, 1, 5, 6],
         [0, 0, 5, 7],
         [7, 3, 6, 1]]])
--------------------------------------------------
torch.Size([6, 5, 4])
--------------------------------------------------
tensor([[[3, 3, 2, 3],
         [4, 4, 2, 4],
         [8, 5, 5, 2],
         [4, 3, 3, 5],
         [2, 8, 4, 5]],

        [[2, 2, 9, 1],
         [4, 7, 9, 5],
         [4

## 2. torch.stack 函数的使用

`torch.stack` 函数可以将两个或多个张量沿着一个**新的维度**进行拼接。也就是说，拼接后的张量会比原张量多出一个维度。

In [27]:
# 2. torch.stack 函数的使用
def test02():

    data1 = torch.randint(0, 10, [2, 3])
    data2 = torch.randint(0, 10, [2, 3])

    print(data1)
    print(data2)
    print('-' * 50)

    # 1. 按 0 维度拼接
    new_data = torch.stack([data1, data2], dim=0)
    print(new_data.shape)
    print('-' * 50)
    print(new_data)
    print('-' * 50)

    # 2. 按 1 维度拼接
    new_data = torch.stack([data1, data2], dim=1)
    print(new_data.shape)
    print('-' * 50)
    print(new_data)
    print('-' * 50)

    # 3. 按 2 维度拼接
    new_data = torch.stack([data1, data2], dim=2)
    print(new_data.shape)
    print(new_data)
    print('-' * 50)


if __name__ == '__main__':
    test02()

tensor([[3, 9, 1],
        [5, 5, 8]])
tensor([[0, 8, 0],
        [1, 9, 7]])
--------------------------------------------------
torch.Size([2, 2, 3])
--------------------------------------------------
tensor([[[3, 9, 1],
         [5, 5, 8]],

        [[0, 8, 0],
         [1, 9, 7]]])
--------------------------------------------------
torch.Size([2, 2, 3])
--------------------------------------------------
tensor([[[3, 9, 1],
         [0, 8, 0]],

        [[5, 5, 8],
         [1, 9, 7]]])
--------------------------------------------------
torch.Size([2, 3, 2])
tensor([[[3, 0],
         [9, 8],
         [1, 0]],

        [[5, 1],
         [5, 9],
         [8, 7]]])
--------------------------------------------------


# 5 张量索引操作

学习目标

- 掌握张量不同索引操作

我们在操作张量时，经常需要去进行获取或者修改操作，掌握张量的花式索引操作是必须的一项能力。

## 1. 简单行、列索引

### 准备数据

In [1]:
import torch

data = torch.randint(0, 10, [4, 5])
print(data)
print('-' * 50)

tensor([[8, 1, 2, 6, 1],
        [7, 9, 1, 2, 5],
        [8, 4, 0, 8, 4],
        [3, 2, 2, 7, 6]])
--------------------------------------------------


In [2]:
# 1. 简单行、列索引
def test01():

    print(data[0])
    print(data[:, 0])
    print('-' * 50)


if __name__ == '__main__':
    test01()

tensor([8, 1, 2, 6, 1])
tensor([8, 7, 8, 3])
--------------------------------------------------


## 2. 列表索引

In [3]:
# 2. 列表索引
def test02():

    # 返回 (0, 1)、(1, 2) 两个位置的元素
    print(data[[0, 1], [1, 2]])
    print('-' * 50)

    # 返回 0、1 行的 1、2 列共 4 个元素
    print(data[[[0], [1]], [1, 2]])


if __name__ == '__main__':
    test02()

tensor([1, 1])
--------------------------------------------------
tensor([[1, 2],
        [9, 1]])


## 3. 范围索引

In [4]:
# 3. 范围索引
def test03():
    # 前 3 行的前 2 列数据
    print(data[:3, :2])
    # 第 2 行到最后的前 2 列数据
    print(data[2:, :2])


if __name__ == '__main__':
    test03()

tensor([[8, 1],
        [7, 9],
        [8, 4]])
tensor([[8, 4],
        [3, 2]])


## 4. 布尔索引

In [7]:
# 布尔索引
def test04():

    # 第 2 列大于 5 的行数据
    print(data[data[:, 2] > 5])
    # 第 1 行大于 5 的列数据
    print(data[:, data[1] > 5])


if __name__ == '__main__':
    test04()

tensor([], size=(0, 5), dtype=torch.int64)
tensor([[8, 1],
        [7, 9],
        [8, 4],
        [3, 2]])


## 5. 多维索引

In [8]:
# 多维索引
def test05():

    data = torch.randint(0, 10, [3, 4, 5])
    print(data)
    print('-' * 50)

    print(data[0, :, :])
    print(data[:, 0, :])
    print(data[:, :, 0])


if __name__ == '__main__':
    test05()

tensor([[[7, 5, 5, 6, 4],
         [8, 1, 0, 2, 0],
         [4, 8, 5, 7, 8],
         [2, 6, 6, 6, 6]],

        [[1, 5, 6, 4, 3],
         [4, 7, 5, 7, 5],
         [6, 2, 2, 2, 7],
         [4, 5, 6, 0, 8]],

        [[6, 4, 7, 0, 4],
         [3, 3, 4, 5, 8],
         [8, 2, 7, 7, 0],
         [2, 4, 2, 2, 4]]])
--------------------------------------------------
tensor([[7, 5, 5, 6, 4],
        [8, 1, 0, 2, 0],
        [4, 8, 5, 7, 8],
        [2, 6, 6, 6, 6]])
tensor([[7, 5, 5, 6, 4],
        [1, 5, 6, 4, 3],
        [6, 4, 7, 0, 4]])
tensor([[7, 8, 4, 2],
        [1, 4, 6, 4],
        [6, 3, 8, 2]])
