# 5 张量索引操作

学习目标

- 掌握张量不同索引操作

我们在操作张量时，经常需要去进行获取或者修改操作，掌握张量的花式索引操作是必须的一项能力。

## 1. 简单行、列索引

### 准备数据

In [ ]:
import torch

data = torch.randint(0, 10, [4, 5])
print(data)
print('-' * 50)

tensor([[8, 1, 2, 6, 1],
        [7, 9, 1, 2, 5],
        [8, 4, 0, 8, 4],
        [3, 2, 2, 7, 6]])
--------------------------------------------------


In [ ]:
# 1. 简单行、列索引
def test01():

    print(data[0])
    print(data[:, 0])
    print('-' * 50)


if __name__ == '__main__':
    test01()

tensor([8, 1, 2, 6, 1])
tensor([8, 7, 8, 3])
--------------------------------------------------


## 2. 列表索引

In [ ]:
# 2. 列表索引
def test02():

    # 返回 (0, 1)、(1, 2) 两个位置的元素
    print(data[[0, 1], [1, 2]])
    print('-' * 50)

    # 返回 0、1 行的 1、2 列共 4 个元素
    print(data[[[0], [1]], [1, 2]])


if __name__ == '__main__':
    test02()

tensor([1, 1])
--------------------------------------------------
tensor([[1, 2],
        [9, 1]])


## 3. 范围索引

In [ ]:
# 3. 范围索引
def test03():
    # 前 3 行的前 2 列数据
    print(data[:3, :2])
    # 第 2 行到最后的前 2 列数据
    print(data[2:, :2])


if __name__ == '__main__':
    test03()

tensor([[8, 1],
        [7, 9],
        [8, 4]])
tensor([[8, 4],
        [3, 2]])


## 4. 布尔索引

In [ ]:
# 布尔索引
def test04():

    # 第 2 列大于 5 的行数据
    print(data[data[:, 2] > 5])
    # 第 1 行大于 5 的列数据
    print(data[:, data[1] > 5])


if __name__ == '__main__':
    test04()

tensor([], size=(0, 5), dtype=torch.int64)
tensor([[8, 1],
        [7, 9],
        [8, 4],
        [3, 2]])


## 5. 多维索引

In [ ]:
# 多维索引
def test05():

    data = torch.randint(0, 10, [3, 4, 5])
    print(data)
    print('-' * 50)

    print(data[0, :, :])
    print(data[:, 0, :])
    print(data[:, :, 0])


if __name__ == '__main__':
    test05()

tensor([[[7, 5, 5, 6, 4],
         [8, 1, 0, 2, 0],
         [4, 8, 5, 7, 8],
         [2, 6, 6, 6, 6]],

        [[1, 5, 6, 4, 3],
         [4, 7, 5, 7, 5],
         [6, 2, 2, 2, 7],
         [4, 5, 6, 0, 8]],

        [[6, 4, 7, 0, 4],
         [3, 3, 4, 5, 8],
         [8, 2, 7, 7, 0],
         [2, 4, 2, 2, 4]]])
--------------------------------------------------
tensor([[7, 5, 5, 6, 4],
        [8, 1, 0, 2, 0],
        [4, 8, 5, 7, 8],
        [2, 6, 6, 6, 6]])
tensor([[7, 5, 5, 6, 4],
        [1, 5, 6, 4, 3],
        [6, 4, 7, 0, 4]])
tensor([[7, 8, 4, 2],
        [1, 4, 6, 4],
        [6, 3, 8, 2]])
