# 4 张量拼接操作

学习目标
- 掌握 torch.cat torch.stack 使用

张量的拼接操作在神经网络搭建过程中是非常常用的方法，例如：在后面将要学习到的残差网络、注意力机制中都使用到了张量拼接。

## 1. torch.cat 函数的使用

`torch.cat` 函数可以将两个张量根据指定的维度拼接起来。

In [1]:
import torch


def test():

    data1 = torch.randint(0, 10, [3, 5, 4])
    data2 = torch.randint(0, 10, [3, 5, 4])

    print(data1)
    print(data2)
    print('-' * 50)

    # 1. 按 0 维度拼接
    new_data = torch.cat([data1, data2], dim=0)
    print(new_data.shape)
    print('-' * 50)
    print(new_data)
    print('-' * 50)

    # 2. 按 1 维度拼接
    new_data = torch.cat([data1, data2], dim=1)
    print(new_data.shape)
    print('-' * 50)
    print(new_data)
    print('-' * 50)

    # 3. 按 2 维度拼接
    new_data = torch.cat([data1, data2], dim=2)
    print(new_data.shape)
    print(new_data)
    print('-' * 50)

if __name__ == '__main__':
    test()

tensor([[[6, 3, 6, 7],
         [4, 5, 8, 3],
         [7, 2, 7, 1],
         [0, 7, 1, 2],
         [3, 3, 3, 2]],

        [[2, 4, 3, 9],
         [9, 9, 2, 7],
         [1, 4, 8, 4],
         [4, 6, 2, 1],
         [7, 4, 0, 0]],

        [[5, 4, 1, 4],
         [7, 4, 8, 5],
         [9, 5, 5, 1],
         [4, 5, 2, 8],
         [7, 8, 6, 3]]])
tensor([[[1, 7, 8, 2],
         [8, 7, 1, 6],
         [5, 8, 1, 1],
         [7, 9, 7, 4],
         [2, 1, 5, 3]],

        [[1, 7, 8, 8],
         [9, 8, 5, 6],
         [7, 1, 2, 5],
         [1, 4, 5, 4],
         [6, 5, 8, 1]],

        [[7, 4, 0, 0],
         [4, 2, 3, 4],
         [9, 2, 3, 8],
         [9, 9, 1, 6],
         [6, 9, 3, 9]]])
--------------------------------------------------
torch.Size([6, 5, 4])
--------------------------------------------------
tensor([[[6, 3, 6, 7],
         [4, 5, 8, 3],
         [7, 2, 7, 1],
         [0, 7, 1, 2],
         [3, 3, 3, 2]],

        [[2, 4, 3, 9],
         [9, 9, 2, 7],
         [1

## 2. torch.stack 函数的使用

`torch.stack` 函数可以将两个或多个张量沿着一个**新的维度**进行拼接。也就是说，拼接后的张量会比原张量多出一个维度。

In [ ]:
# 2. torch.stack 函数的使用
def test02():

    data1 = torch.randint(0, 10, [2, 3])
    data2 = torch.randint(0, 10, [2, 3])

    print(data1)
    print(data2)
    print('-' * 50)

    # 1. 按 0 维度拼接
    new_data = torch.stack([data1, data2], dim=0)
    print(new_data.shape)
    print('-' * 50)
    print(new_data)
    print('-' * 50)

    # 2. 按 1 维度拼接
    new_data = torch.stack([data1, data2], dim=1)
    print(new_data.shape)
    print('-' * 50)
    print(new_data)
    print('-' * 50)

    # 3. 按 2 维度拼接
    new_data = torch.stack([data1, data2], dim=2)
    print(new_data.shape)
    print(new_data)
    print('-' * 50)


if __name__ == '__main__':
    test02()

tensor([[3, 9, 1],
        [5, 5, 8]])
tensor([[0, 8, 0],
        [1, 9, 7]])
--------------------------------------------------
torch.Size([2, 2, 3])
--------------------------------------------------
tensor([[[3, 9, 1],
         [5, 5, 8]],

        [[0, 8, 0],
         [1, 9, 7]]])
--------------------------------------------------
torch.Size([2, 2, 3])
--------------------------------------------------
tensor([[[3, 9, 1],
         [0, 8, 0]],

        [[5, 5, 8],
         [1, 9, 7]]])
--------------------------------------------------
torch.Size([2, 3, 2])
tensor([[[3, 0],
         [9, 8],
         [1, 0]],

        [[5, 1],
         [5, 9],
         [8, 7]]])
--------------------------------------------------
