# 第1章 预备知识

## 1.1 数据操作

## 1.1.1 创建Tensor

导入PyTorch

In [1]:
import torch
print("版本号为：{}".format(torch.__version__))

版本号为：2.4.0+cpu


创建行向量

In [2]:
tensor_a = torch.arange(0, 12)
tensor_a

tensor([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [3]:
print("张量的存储位置：{}".format(tensor_a.device))

张量的存储位置：cpu


获取张量的形状

In [4]:
tensor_a.shape

torch.Size([12])

获取张量中元素总数

In [5]:
tensor_a.numel()

12

维度变换

In [6]:
X = tensor_a.view(3, 4)
X

tensor([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]])

In [7]:
X = tensor_a.view(3, -1)
X

tensor([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]])

In [8]:
X = tensor_a.view(-1, 4)
X

tensor([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]])

全0张量

In [9]:
torch.zeros((2, 3, 4))

tensor([[[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]])

全1张量

In [10]:
torch.ones((3, 4))

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

通过列表创建张量

In [11]:
Y = torch.tensor([[2, 1, 4, 3], [1, 2, 3, 4], [4, 3, 2, 1]])
Y

tensor([[2, 1, 4, 3],
        [1, 2, 3, 4],
        [4, 3, 2, 1]])

正态分布随机初始化张量的值

In [12]:
torch.randn((3, 4))

tensor([[ 0.3686, -0.3449,  1.1056, -0.8109],
        [-1.4087,  0.6807, -0.3320, -1.1130],
        [ 0.0849,  0.1692, -0.8162, -1.3913]])

## 1.1.2 运算

按元素加法

In [48]:
print(X)
print(Y)
X + Y

tensor([[ 2,  3,  8,  9],
        [25, 26, 27, 28],
        [20, 21, 22, 23]])
tensor([[ 2,  2,  6,  6],
        [13, 14, 15, 16],
        [12, 12, 12, 12]])


tensor([[ 4,  5, 14, 15],
        [38, 40, 42, 44],
        [32, 33, 34, 35]])

按元素乘法

In [50]:
print(X)
print(Y)
X * Y

tensor([[ 2,  3,  8,  9],
        [25, 26, 27, 28],
        [20, 21, 22, 23]])
tensor([[ 2,  2,  6,  6],
        [13, 14, 15, 16],
        [12, 12, 12, 12]])


tensor([[  4,   6,  48,  54],
        [325, 364, 405, 448],
        [240, 252, 264, 276]])

按元素除法

In [52]:
print(X.float())
print(Y.float())
X.float() / Y.float()

tensor([[ 2.,  3.,  8.,  9.],
        [25., 26., 27., 28.],
        [20., 21., 22., 23.]])
tensor([[ 2.,  2.,  6.,  6.],
        [13., 14., 15., 16.],
        [12., 12., 12., 12.]])


tensor([[1.0000, 1.5000, 1.3333, 1.5000],
        [1.9231, 1.8571, 1.8000, 1.7500],
        [1.6667, 1.7500, 1.8333, 1.9167]])

按元素做指数运算

In [60]:
print(Y.float())
# e^x
torch.exp(Y.float())

tensor([[ 2.,  2.,  6.,  6.],
        [13., 14., 15., 16.],
        [12., 12., 12., 12.]])


tensor([[7.3891e+00, 7.3891e+00, 4.0343e+02, 4.0343e+02],
        [4.4241e+05, 1.2026e+06, 3.2690e+06, 8.8861e+06],
        [1.6275e+05, 1.6275e+05, 1.6275e+05, 1.6275e+05]])

矩阵乘法

In [64]:
X @ Y.t()

tensor([[ 112,  332,  264],
        [ 432, 1542, 1272],
        [ 352, 1252, 1032]])

纵向拼接与横向拼接

In [18]:
torch.cat((X, Y), 0), torch.cat((X, Y), 1)

(tensor([[ 0,  1,  2,  3],
         [ 4,  5,  6,  7],
         [ 8,  9, 10, 11],
         [ 2,  1,  4,  3],
         [ 1,  2,  3,  4],
         [ 4,  3,  2,  1]]),
 tensor([[ 0,  1,  2,  3,  2,  1,  4,  3],
         [ 4,  5,  6,  7,  1,  2,  3,  4],
         [ 8,  9, 10, 11,  4,  3,  2,  1]]))

条件判别式

In [19]:
X == Y

tensor([[False,  True, False,  True],
        [False, False, False, False],
        [False, False, False, False]])

张量内元素求和

In [20]:
torch.sum(X)

tensor(66)

计算结果转换为标量

In [21]:
torch.norm(X.float()).item()

22.494443893432617

## 1.1.3 广播机制

创建张量

In [22]:
A = torch.arange(0, 3).view(3, 1)
B = torch.arange(0, 2).view(1, 2)
A, B

(tensor([[0],
         [1],
         [2]]),
 tensor([[0, 1]]))

In [23]:
A + B

tensor([[0, 1],
        [1, 2],
        [2, 3]])

### 1.1.4 索引

In [24]:
X[1:3]

tensor([[ 4,  5,  6,  7],
        [ 8,  9, 10, 11]])

修改张量中某位置元素的值

In [25]:
X[1, 2] = 9
X

tensor([[ 0,  1,  2,  3],
        [ 4,  5,  9,  7],
        [ 8,  9, 10, 11]])

对部分元素重新赋值

In [26]:
X[1:2, :] = 12
X

tensor([[ 0,  1,  2,  3],
        [12, 12, 12, 12],
        [ 8,  9, 10, 11]])

### 1.1.5 运算的内存开销

内存不同

In [27]:
before = id(Y)
Y = Y + X
id(Y) == before

False

内存相同

In [28]:
Z = torch.zeros_like(Y)
before = id(Z)
Z[:] = X + Y
id(Z) == before

True

In [29]:
torch.add(X, Y, out=Z)
id(Z) == before

True

In [30]:
before = id(X)
X += Y
id(X) == before

True

### 1.1.6 Tensor和NumPy相互变换

将NumPy变换为Tensor

In [31]:
import numpy as np
P = np.ones((2, 3))
D = torch.from_numpy(P)
D

tensor([[1., 1., 1.],
        [1., 1., 1.]], dtype=torch.float64)

将Tensor变换为NumPy

In [32]:
D.numpy()

array([[1., 1., 1.],
       [1., 1., 1.]])

## 1.2 自动求梯度

In [33]:
from torch import autograd

### 1.2.1 简单例子

In [34]:
x = torch.arange(4).float()
x

tensor([0., 1., 2., 3.])

In [35]:
x.requires_grad_(True)

tensor([0., 1., 2., 3.], requires_grad=True)

In [36]:
y = 2*torch.dot(x, x.t())

In [37]:
y.backward()

In [38]:
print(x.grad)

tensor([ 0.,  4.,  8., 12.])


## 1.3 查阅文档

In [39]:
print(dir(torch.random))

['Generator', '__builtins__', '__cached__', '__doc__', '__file__', '__loader__', '__name__', '__package__', '__spec__', '_fork_rng_warned_already', '_seed_custom_device', 'contextlib', 'default_generator', 'fork_rng', 'get_rng_state', 'initial_seed', 'manual_seed', 'seed', 'set_rng_state', 'torch', 'warnings']


In [40]:
help(torch.ones_like)

Help on built-in function ones_like in module torch:

ones_like(...)
    ones_like(input, *, dtype=None, layout=None, device=None, requires_grad=False, memory_format=torch.preserve_format) -> Tensor

    Returns a tensor filled with the scalar value `1`, with the same size as
    :attr:`input`. ``torch.ones_like(input)`` is equivalent to
    ``torch.ones(input.size(), dtype=input.dtype, layout=input.layout, device=input.device)``.

    .. warning::
        As of 0.4, this function does not support an :attr:`out` keyword. As an alternative,
        the old ``torch.ones_like(input, out=output)`` is equivalent to
        ``torch.ones(input.size(), out=output)``.

    Args:
        input (Tensor): the size of :attr:`input` will determine size of the output tensor.

    Keyword arguments:
        dtype (:class:`torch.dtype`, optional): the desired data type of returned Tensor.
            Default: if ``None``, defaults to the dtype of :attr:`input`.
        layout (:class:`torch.layout`, op

In [41]:
x = torch.tensor([[0, 0, 0], [2, 2, 2]])
y = torch.ones_like(x)
y

tensor([[1, 1, 1],
        [1, 1, 1]])

In [42]:
torch.ones_like?

In [43]:
torch.ones_like??