# NumPy
## 1.1 Numpy简介
一个基于python的扩展库
提供高维数组对象ndarray，运算速度碾压python List
提供了各种高级数据编程工具，如矩阵运算、向量运算、快速筛选、I/O操作，博里叶变换、线性代数，随机数等
## 1.2 ndarray属性
1. ndim:维度
2. shape:形状(各维度的长度)
3. size:总长度
4. dype:元素类型

## 1.3 创建ndarray

In [42]:
import numpy as np

In [43]:
arr1 = np.array([1,2,3])

In [44]:
type(arr1)

numpy.ndarray

In [45]:
arr1.ndim

1

In [46]:
arr1.shape

(3,)

In [47]:
arr1.size

3

In [48]:
arr1.dtype

dtype('int64')

In [49]:
arr2 = np.array([[1,2,3],[4,5,6]])
arr2

array([[1, 2, 3],
       [4, 5, 6]])

In [50]:
arr2.ndim, arr2.shape, arr2.size, arr2.dtype

(2, (2, 3), 6, dtype('int64'))

### 1.3.1 使用np.array()由python list创建
display print output

In [51]:
print(arr2)

[[1 2 3]
 [4 5 6]]


In [52]:
display(arr2)

array([[1, 2, 3],
       [4, 5, 6]])

In [53]:
display(arr1, arr2)

array([1, 2, 3])

array([[1, 2, 3],
       [4, 5, 6]])

In [54]:
arr2

array([[1, 2, 3],
       [4, 5, 6]])

### 1.3.2 强制类型统一

numpy设计初衷时用于运算的，所以对数据类型进行统一优化

注意:
- numpy默认ndarray的所有元素的类型是相同的

- 如果传进来的列表中包含不同的类型，则统一为同一类型，优先级:str>float>int

In [55]:
list1 = [1, 2, 3, 4.12]
list1

[1, 2, 3, 4.12]

In [56]:
arr3 = np.array(list1)

In [57]:
arr3.dtype

dtype('float64')

In [58]:
list2 = [1, 2, 3, 3.14, 'object']
arr4 = np.array(list2)

In [59]:
# U 表示Unicode的简写形式
arr4.dtype

dtype('<U32')

In [60]:
type(arr2) # 查看arr2对象本身的类型

numpy.ndarray

In [61]:
arr2.dtype # 查看arr2内部的元素类型，由于ndarray的元素类型是强制统一的，所以只返回一个类型

dtype('int64')

### 1.3.3 Numpy中的数据类型

### 1.3.4 使用np的routines函数创建


1. np.ones(shape, dtype=None, order='C')
shape: 形状，使用元组表示

In [62]:
np.ones(shape=(2,3))

array([[1., 1., 1.],
       [1., 1., 1.]])

In [63]:
np.ones(shape=3)

array([1., 1., 1.])

In [64]:
np.ones(shape=(1,3))

array([[1., 1., 1.]])

In [65]:
np.ones(shape=(3,1))

array([[1.],
       [1.],
       [1.]])

In [66]:
np.ones(shape=(3,2), dtype=np.int8)

array([[1, 1],
       [1, 1],
       [1, 1]], dtype=int8)

2. np.zeros(shape, dtype=float, order='C')

In [67]:
np.zeros(shape=(3,1),dtype=np.uint8)

array([[0],
       [0],
       [0]], dtype=uint8)

3. np.full(shape, fill value, dtype=None, order='C')

In [68]:
np.full(shape=(3,3), fill_value=6)

array([[6, 6, 6],
       [6, 6, 6],
       [6, 6, 6]])

4. np.eye(N, M=None, k=0, dtype=float)

In [70]:
np.eye(N=3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [71]:
np.eye(N=3, M=2)

array([[1., 0.],
       [0., 1.],
       [0., 0.]])

In [72]:
np.eye(N=3, k=1) # np.eye(N=3, k=-1)

array([[0., 1., 0.],
       [0., 0., 1.],
       [0., 0., 0.]])

5. np.linspace(start, stop, num=50, endpoint=True, retstep=False, dtype=None)

In [74]:
np.linspace(0, 10, 11)

array([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])

In [77]:
np.linspace(0, 100, 10, endpoint=False) 

array([ 0., 10., 20., 30., 40., 50., 60., 70., 80., 90.])

In [ ]:
np.linspace(0, 360, 4, endpoint=False)

array([  0., 120., 240., 360.])

6. np.arange([start, ]stop, [step, ]dtype=None)

In [80]:
np.arange(0, 100, step=10)

array([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])

7. np.random.randint(low,high=None,size=None. dtype='l')

In [81]:
np.random.randint(low=0, high=100, size=(3,5))

array([[77, 70, 52,  8, 59],
       [35, 78, 10, 62, 35],
       [42, 74, 14, 82, 52]], dtype=int32)

In [82]:
np.random.randint(0,10, size=(10,))

array([0, 0, 7, 7, 0, 8, 3, 9, 6, 3], dtype=int32)

8. 正态分布函数
- np.random.randn(d0, d1, ..., dn)标准正态分布
- np.random.normal() 普通正态分布

9. np.random.random(size=None)
生成0到1的随机数，左闭右开