# 1.Numpy进阶

In [1]:
import numpy as np

## 1.1 Numpy数组操作

### 1.1.1 添加元素

numpy. append函数在数组的末尾添加值。追加操作会分配整个数组，并把原来的数组复制到新数组中

注意：

1. 插入的维度要保证所有数组的长度是相同的
2. 如果没有指定轴，数组会被扁平处理

In [ ]:
data = [1,2,3,4]

In [3]:
data.append(5)

In [4]:
arr = np.array(data)
data

[1, 2, 3, 4, 5]

In [5]:
arr.append(5)

AttributeError: 'numpy.ndarray' object has no attribute 'append'

In [6]:
np.append(arr, 8)

array([1, 2, 3, 4, 5, 8])

In [7]:
arr2 = np. random. randint(0, 10, size=(4,3))
arr2

array([[6, 0, 5],
       [3, 3, 2],
       [8, 5, 4],
       [4, 6, 2]])

In [12]:
np.append(arr2, [[1,2,3]], axis=0)

array([[6, 0, 5],
       [3, 3, 2],
       [8, 5, 4],
       [4, 6, 2],
       [1, 2, 3]])

In [13]:
data = np.ones(shape=(4,1))
data

array([[1.],
       [1.],
       [1.],
       [1.]])

In [14]:
arr2

array([[6, 0, 5],
       [3, 3, 2],
       [8, 5, 4],
       [4, 6, 2]])

In [15]:
np.append(arr2, data, axis=1)

array([[6., 0., 5., 1.],
       [3., 3., 2., 1.],
       [8., 5., 4., 1.],
       [4., 6., 2., 1.]])

### 1.1.2 插入元素

numpy. insert函数在给定索引之前，沿给定轴在输入数组中插入值

如果未提供轴，则输入数组会被展开

In [16]:
arr

array([1, 2, 3, 4, 5])

In [18]:
np.insert(arr, 2, 100)

array([  1,   2, 100,   3,   4,   5])

In [17]:
arr2

array([[6, 0, 5],
       [3, 3, 2],
       [8, 5, 4],
       [4, 6, 2]])

In [21]:
np.insert(arr2, 2, [1,1,1], axis=0)

array([[6, 0, 5],
       [3, 3, 2],
       [1, 1, 1],
       [8, 5, 4],
       [4, 6, 2]])

### 1.1.3 删除元素

numpy. delete函数返回从输入数组中删除指定子数组的新数组。
如果未提供轴参数，则输入数组将展开。

In [ ]:
arr

array([1, 2, 3, 4, 5])

In [23]:
np.delete(arr, 1)

array([1, 3, 4, 5])

In [24]:
arr2

array([[6, 0, 5],
       [3, 3, 2],
       [8, 5, 4],
       [4, 6, 2]])

In [27]:
np.delete(arr2, 1, axis=0)

array([[6, 0, 5],
       [8, 5, 4],
       [4, 6, 2]])

### 1.1.4 数组变形reshape

numpy. reshape函数可以在不改变数据的条件下修改形状，格式如下：numpy. reshape(arr,newshape,order='C')
- arr:要修改形状的数组
- newshape:整数或者整数数组，新的形状应当兼容原有形状
- order: 'C'--按行，'F'--按列，'A'--原顺序，'K'--元素在内存中的出现顺序。

In [28]:
arr = np.random.randint(0, 10, size=8)
arr

array([1, 9, 1, 8, 4, 0, 4, 4])

In [34]:
# 不能显示使用shape
# 发现了一些现象： 在numpy中，有些函数的参数名可以写，有些不能写。
arr.reshape((2,4), order="C")

array([[1, 9, 1, 8],
       [4, 0, 4, 4]])

In [33]:
arr.reshape((2,4), order="F")

array([[1, 1, 4, 4],
       [9, 8, 0, 4]])

### 1.1.5 数组迭代器

numpy.ndarray.flat

In [35]:
for i in arr:
    print(i)

1
9
1
8
4
0
4
4


In [36]:
arr2

array([[6, 0, 5],
       [3, 3, 2],
       [8, 5, 4],
       [4, 6, 2]])

In [37]:
for i in arr2:
    print(i)
    print('------')

[6 0 5]
------
[3 3 2]
------
[8 5 4]
------
[4 6 2]
------


In [39]:
for arr1 in arr2:
    for i in arr1:
        print(i)

6
0
5
3
3
2
8
5
4
4
6
2


In [38]:
for i in arr2.flat:
    print(i)

6
0
5
3
3
2
8
5
4
4
6
2


### 1.1.6 数组扁平处理

numpy.ndarray.flatten()返回一份展开的数组拷贝，对拷贝所做的修改不会影响原始数组

numpy. ravel()展平的数组元素，返回一个展开的数组引用，修改会影响原始数组。

In [40]:
arr2

array([[6, 0, 5],
       [3, 3, 2],
       [8, 5, 4],
       [4, 6, 2]])

In [41]:
arr2.flatten()

array([6, 0, 5, 3, 3, 2, 8, 5, 4, 4, 6, 2])

In [42]:
arr2.ravel()

array([6, 0, 5, 3, 3, 2, 8, 5, 4, 4, 6, 2])

### 1.1.7 数组翻转

numpy.transpose 对换数组的维度

In [43]:
arr2.shape

(4, 3)

In [44]:
arr2

array([[6, 0, 5],
       [3, 3, 2],
       [8, 5, 4],
       [4, 6, 2]])

In [45]:
arr2.transpose([1,0])

array([[6, 3, 8, 4],
       [0, 3, 5, 6],
       [5, 2, 4, 2]])

## 1.2 Numpy 数学函数

### 1.2.1 三角函数

- np.sin()
- np.cos()
- np.tan()

接收的参数是弧度，不是角度

In [46]:
np.pi

3.141592653589793

In [47]:
#生成一个取值范围在-pi~pi之间的数组
data=np.random.random(size=10)*2*np.pi-np.pi

In [48]:
data

array([ 1.16743049,  2.1128144 ,  0.95142428, -1.84270427, -2.89862433,
       -2.57160818, -2.37023938,  2.8865268 ,  2.52862488, -1.16271297])

In [49]:
np.sin(data)

array([ 0.91974506,  0.85666937,  0.81424316, -0.96326023, -0.24058482,
       -0.53961898, -0.69710613,  0.25230913,  0.57529746, -0.91788313])

In [50]:
np.sin(90), np.sin(np.pi/2)

(0.8939966636005579, 1.0)

### 1.2.2 舍入函数

numpy.around()

- a:数组
- decimals：舍入的小数位数。默认值为0。如果为负，整数将四舍五入到小数点左侧的位置

In [53]:
data = np.random.random(size=(10))

In [54]:
np.around(data, 3)

array([0.41 , 0.146, 0.775, 0.871, 0.776, 0.816, 0.169, 0.648, 0.252,
       0.954])

## 1.3 算数函数

加减乘除: add(), subtract(), multiply()和divide()

numpy.power()幂运算，可以做开方运算

numpy.mode()求余运算

np.log（）自然底数的对数np.log2（）,np.log10（）

In [58]:
a1 = np.random.randint(0, 10, size=(5,3))
b1 = np.random.randint(0, 10, size=3)

In [59]:
np.add(a1, b1)

array([[11, 11, 11],
       [ 6, 12,  6],
       [ 6, 15,  5],
       [ 8,  7,  8],
       [ 6,  6,  7]])

In [60]:
data = np.random.randint(0, 10, size=5)
data

array([5, 5, 0, 7, 8])

In [65]:
data_s = np.power(data, 2)

In [66]:
np.power(data_s,1/2)

array([5., 5., 0., 7., 8.])

In [67]:
np.mod(data, 2)

array([1, 1, 0, 1, 0])

In [68]:
# 自然底数
np.e

2.718281828459045

In [69]:
np.log10(100)

2.0

## 1.4 Numpy查找和排序

### 1.4.1 查找索引

numpy.argmax()和numpy.argmin()

In [70]:
data = np. random. randint(0, 100, size=10)
data

array([ 0, 88, 45, 16, 56, 22, 86, 77, 53, 19])

In [71]:
data.argmax(), data.argmin()

(1, 0)

### 1.4.2 条件查找

numpy.where()函数返回输入数组中满足给定条件的元素的索引

In [72]:
data

array([ 0, 88, 45, 16, 56, 22, 86, 77, 53, 19])

conditidon 条件 条件表达式

In [73]:
data > 60

array([False,  True, False, False, False, False,  True,  True, False,
       False])

In [75]:
# condition 参数就是一个条件表达式
condition = data > 60
np. where(condition)

(array([1, 6, 7]),)

### 1.4.3 快速排序

np.sort()与ndarray.sort()都可以，但有区别：
- np.sort()不改变输入
- ndarray.sort()本地处理，不占用空间，但改变输入


numpy.sort()函数返回输入数组的排序副本

In [78]:
arr

array([1, 9, 1, 8, 4, 0, 4, 4])

In [79]:
np.sort(arr)

array([0, 1, 1, 4, 4, 4, 8, 9])

In [80]:
arr

array([1, 9, 1, 8, 4, 0, 4, 4])

In [ ]:
arr.sort()

In [82]:
arr

array([0, 1, 1, 4, 4, 4, 8, 9])

### 1.4.4 索引排序

numpy.argsort()函数返回的是数组值从小到大的索引值。

In [83]:
data = np. random. randint(0, 10, size=5)
data

array([4, 7, 7, 7, 2])

In [84]:
np.argsort(data)

array([4, 0, 1, 2, 3])

### 1.4.5 部分排序

np.partition(a,k)

有的时候我们不是对全部数据感兴趣，我们可能只对最小或最大的一部分感兴趣。
- 当k为正时，我们想要得到最小的k个数
- 当k为负时，我们想要得到最大的k个数

In [86]:
data = np.random.permutation(10000)

In [87]:
data

array([2735, 4762, 7349, ..., 9773, 5542, 5070])

In [89]:
np.partition(data, -2)[-2:]

array([9998, 9999])

In [91]:
np.partition(data, 2)[:2]

array([0, 1])